sale_contracts = {}
purchase_contracts = {}
sale_transaction = {}
purchase_transaction = {}
inventory_sale = {}
existing_contracts = {}
payments_temp = {}
receipt_temp ={}
pay_receip_temp = {}
bank_temp = {}
cash_temp = {}
client_temp ={}
bank_ind_temp = {}
tax_temp = {}